imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: config_admin.yml}

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'CmfMediaBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles: [ CmfCreateBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        path:     %database_path%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en: [fr, de]
            de: [en, fr]
            fr: [en, de]

knp_menu:
    twig: true

cmf_core:
    persistence:
        phpcr:
            enabled: true
            basepath: /cms
    multilang:
        locales: %locales%

cmf_simple_cms:
    routing:
        controllers_by_type:
            schedule: dbu_conference.controller.schedule:scheduleAction
        templates_by_class:
            Dbu\ConferenceBundle\Document\Presentation: DbuConferenceBundle:Page:presentation.html.twig
            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page: DbuConferenceBundle:Page:index.html.twig

cmf_block:
    persistence:
        phpcr:
            block_basepath: /cms

cmf_media:
    imagine_filters:
        upload_thumbnail: image_upload_thumbnail
    extra_filters:
        - portrait_small
        - portrait_large

liip_imagine:
    filter_sets:
        portrait_small:
            data_loader: cmf_media_doctrine_phpcr
            format: jpg
            filters:
                thumbnail: { size: [30, 30], mode: outbound }
        portrait_large:
            data_loader: cmf_media_doctrine_phpcr
            format: jpg
            filters:
                upscale: { min: [130, 130] }
                thumbnail: { size: [130, 130], mode: outbound }
        image_upload_thumbnail:
            data_loader: cmf_media_doctrine_phpcr
            format: jpg
            filters:
                thumbnail: { size: [120, 120], mode: outbound }

fos_rest:
    view:
        formats:
            json: true

lunetics_locale:
    strict_mode: true
    guessing_order:
        - router
        - cookie
        - browser
    allowed_locales: %locales%


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
